[package]
name = "prost-minimal"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.8.0"

[build-dependencies]
prost-build = "0.8.0"
